export default {
  SET_CREDENTIALS: "SET_CREDENTIALS",
  SET_AUTHENTICATED: "SET_AUTHENTICATED",
  AUTH_TOKEN: "AUTH_TOKEN",
  MODE: "MODE",
  USER_DATA: "USER_DATA",
  PAGE_DETAILS: "PAGE_DETAILS",
  MODAL_ACTION: "MODAL_ACTION",
  FORMDATA: "FORMDATA",
  MODAL_BTN_LOADING:"MODAL_BTN_LOADING",
  LOADING:"LOADING"
};
